import { createClient } from '@supabase/supabase-js'
const supabaseUrl ='https://ilvvqvgzlafhevagjoih.supabase.co'
const supabaseAnonKey ='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlsdnZxdmd6bGFmaGV2YWdqb2loIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NDcyNDQsImV4cCI6MjA2ODIyMzI0NH0.APYmXalB5-RfEIKqYnuS4M1-UKeD9TAjBxYy4VqR_nA'
export const supabase= createClient(supabaseUrl,supabaseAnonKey)